### ISSUE TITLE
Code reproduction error

### ISSUE THREAD

**Issue by JunsFu** [skystarhyw/SUGRM#1]
![image](https://github.com/skystarhyw/SUGRM/assets/100461491/25fbc810-7f71-4ea5-9f3a-e97b9add396c)
![image](https://github.com/skystarhyw/SUGRM/assets/100461491/ffc78f10-e552-41e3-9a81-a7573ea91731)
First of all, thank you for all your hard work!
I encountered the following error when running the code:
As shown in Part A of Figure 1: I have completed running the code and have obtained the .csv file results, but the system is still running, and the error in Part B of Figure 1 occurs (Figure 2 is the follow-up of Figure 1B part).
Looking forward to your answer, thank you!

**Comment by skystarhyw** [comment]
Hi,

Thanks for being interested in my work.
The code runs well on my computer without any error so I believe the
problem is a pytorch version issue.
I'm not sure which pytorch version you are using to run this code, but try
using pytorch version '1.7.1' (this is what I use to run the code).
Also, can you elaborate on Part A? Which part of the code ran exactly?
Were you able to run the entire epoch or did the error occur in the middle
of the epoch?
If you were able to run the code for the entire epoch, I don't understand
how the code could throw an error after running it successfully.
Just by looking at the error message, the pytorch version mismatch is my
guess. But if that doesn't solve the problem, please let me know.
Thanks!

Yewon


2024년 1월 12일 (금) 오후 1:42, Juns_Fu ***@***.***>님이 작성:
